preset_values:
  log_levels:
    none: &none 0
    critical: &critical 1
    error: &error 2
    warning: &warning 3
    info: &info 4
    debug: &debug 5

db_service:
  db_server:
    db_host: "127.0.0.0" # Overwritten by env var "DB_HOST"
    db_port: 5432 # Overwritten by env var "DB_PORT"
    db_name: "smart_home" # Overwritten by env var "DB_NAME"
    db_user: "smart_home_admin" # Overwritten by env var "DB_USER"
    db_password: "insert_password"  # Overwritten by env var "DB_PASSWORD"
    db_connections: 4
  logging:
    log_level: *info
    enable_console_log_output: true
    log_file:
      enabled: true
      create_new: true
      archive_old: true
      path: "/var/log/smarthome/db-service.log"
  ipc:
    tcp:
      enabled: true
      address: "127.0.0.1"
      port: 43321
    uds:
      enabled: true
      socket_path: "/var/run/smarthomed.sock"