preset_values:
  ipc_server_thread_count:
    half_cpu_cores: &half_cpu_cores -1
    all_cpu_cores: &all_cpu_cores 0
  log_levels:
    none: &none 0
    critical: &critical 1
    error: &error 2
    warning: &warning 3
    info: &info 4
    debug: &debug 5


core:
  mode: "headless"  #TODO add kiosk gui
  logging:
    log_level: *warning
    enable_console_log_output: true
    log_file:
      enabled: true
      create_new: true
      archive_old: true
      path: "/var/log/smarthome/core.log"
  ipc:
    threads: *half_cpu_cores # Exact thread count if value > 0, possible preset values: *all_cpu_cores, *half_cpu_cores
    tcp:
      enabled: true
      address: "127.0.0.1"
      port: 43321
    uds:
      enabled: true
      socket_path: "/var/run/smarthomed.sock"

services:
  mediator:
    enabled: false
    service_type: "Standalone" # TODO implement systemd service along proper mediator implementation
    exec_path: ~ #Option for standalone mode - Default: /usr/local/bin/
    config_path: "/etc/smarthome/mediator.yaml"
