preset_values:
  service_modes:
    standalone_daemon: &standalone_daemon "STANDALONE"
    systemd_daemon: &systemd_daemon "SYSTEMD"
  core_modes:
    headless: &headless 0
    gui: &gui 1
  thread_count_values:
    quarter_cpu_cores: &quarter_cpu_cores -3
    third_cpu_cores: &third_cpu_cores -2
    half_cpu_cores: &half_cpu_cores -1
    all_cpu_cores: &all_cpu_cores 0
    single_thread: &single_thread 1
    two_threads: &two_threads 2
  log_levels:
    none: &none 0
    critical: &critical 1
    error: &error 2
    warning: &warning 3
    info: &info 4
    debug: &debug 5

# Rule for thread count values:
#   value < 0: ceil(all CPU cores / (|value| + 1))
#   value == 0: all CPU cores
#   value >= 1: exact thread count

core:
  mode: *headless
  main_threads: *two_threads # Recommended setting value >= 2
  worker_threads: *single_thread  # Recommended setting value >= 1
  logging:
    log_level: *info
    enable_console_log_output: true
    log_file:
      enabled: true
      create_new: true
      archive_old: true
      path: "/var/log/smarthome/core.log"
  ipc:
    threads: *two_threads # Recommended setting value >= 2
    tcp:
      enabled: true
      address: "127.0.0.1"
      port: 43321
    uds:
      enabled: true
      socket_path: "/var/run/smarthomed.sock"

services:
  mediator:
    enabled: false
    service_type: *standalone_daemon
    exec_path: ~ #Option for standalone mode - Default: /usr/local/bin/
    config_path: "/etc/smarthome/mediator.yaml"

# TODO add more config options for gui
gui:
  logging:
    log_level: *info
    enable_console_log_output: true
    log_file:
      enabled: true
      create_new: true
      archive_old: true
      path: "/var/log/smarthome/gui.log"
