#pragma once

#define BACKGROUND_TASK_PRIORITY 1
#define LOW_TASK_PRIORITY 2
#define MEDIUM_TASK_PRIORITY 3
#define HIGH_TASK_PRIORITY 4
#define CRITICAL_TASK_PRIORITY 5

// WARNING: smaller task size than 1024B is NOT recommended (theoretically the smallest task size for ESP32 is 768B)
#define SMALL_TASK_SIZE 1024 // 1kB
#define MEDIUM_TASK_SIZE 2048 // 2kB
#define BIG_TASK_SIZE 4096 // 4kB
#define HUGE_TASK_SIZE 8192 // 8kB
#define TESTING_TASK_SIZE 10000 // 10000B round number for easy calculations - only for testing

// DebugLED
#define PAIRING_BLINK_TASK_SIZE     MEDIUM_TASK_SIZE
#define RESET_BLINK_TASK_SIZE       MEDIUM_TASK_SIZE
#define POWER_ON_BLINK_TASK_SIZE    SMALL_TASK_SIZE

// PairingButton
#define FACTORY_RESET_TASK_SIZE     BIG_TASK_SIZE
#define TOGGLE_OTA_TASK_SIZE        BIG_TASK_SIZE

// Communication
#define COMMUNICATION_MAIN_TASK_SIZE    BIG_TASK_SIZE
#define ENCODE_TASK_SIZE                MEDIUM_TASK_SIZE
#define DECODE_TASK_SIZE                BIG_TASK_SIZE
#define TERMINAL_INPUT_TASK_SIZE        HUGE_TASK_SIZE

// HC12
#define HC12_MAIN_TASK_SIZE             MEDIUM_TASK_SIZE
#define TRANSMIT_TASK_SIZE              MEDIUM_TASK_SIZE
#define SETUP_HC12_TASK_SIZE            MEDIUM_TASK_SIZE
#define ON_BOOT_SETUP_HC12_TASK_SIZE    MEDIUM_TASK_SIZE

// Addressing
#define MODULE_ADDRESSING_TASK_SIZE         BIG_TASK_SIZE
#define CENTRAL_UNIT_ADDRESSING_TASK_SIZE   BIG_TASK_SIZE

// PowerManager
#define POWER_MANAGEMENT_SEMAPHORE_TIMEOUT  10000 // 10s
#define ENTER_SLEEP_TASK_SIZE               TESTING_TASK_SIZE

// Sensors
#define BATTERY_READ_TASK_SIZE MEDIUM_TASK_SIZE
#define LIGHT_READ_TASK_SIZE MEDIUM_TASK_SIZE
#define DHT22_READ_TASK_SIZE MEDIUM_TASK_SIZE
#define BME280_READ_TASK_SIZE BIG_TASK_SIZE
#define WINDOW_SENSOR_TASK_SIZE BIG_TASK_SIZE

// Ota
#define OTA_TASK_SIZE BIG_TASK_SIZE


#ifdef TESTING_TASK_SIZE
#warning "TESTING_TASK_SIZE defined"
#endif