-- Database generated with pgModeler (PostgreSQL Database Modeler).
-- pgModeler version: 1.0.0-beta1
-- PostgreSQL version: 15.0
-- Project Site: pgmodeler.io
-- Model Author: Paweł Dyczek
-- object: smart_home_admin | type: ROLE --
-- DROP ROLE IF EXISTS smart_home_admin;
CREATE ROLE smart_home_admin WITH LOGIN PASSWORD 'insert_password';
-- ddl-end --


-- Database creation must be performed outside a multi lined SQL file.
-- These commands were put in this file only as a convenience.
--
-- object: smart_home | type: DATABASE --
-- DROP DATABASE IF EXISTS smart_home;
-- CREATE DATABASE smart_home;
-- ddl-end --


SET
check_function_bodies = false;
-- ddl-end --


-- object: public.modules | type: TABLE --
-- DROP TABLE IF EXISTS public.modules CASCADE;
CREATE TABLE public.modules
(
    id            integer     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    logic_address smallint    NOT NULL,
    name          varchar(64) NOT NULL,
    config        jsonb       NOT NULL,
    last_online   timestamptz,
    created_at    timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_modules_id PRIMARY KEY (id),
    CONSTRAINT unq_logic_address UNIQUE (logic_address)
);
-- ddl-end --
ALTER TABLE public.modules OWNER TO smart_home_admin;
-- ddl-end --

-- object: public.devices | type: TABLE --
-- DROP TABLE IF EXISTS public.devices CASCADE;
CREATE TABLE public.devices
(
    id         integer     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    logic_id   smallint    NOT NULL,
    name       varchar(64) NOT NULL,
    type       varchar(64) NOT NULL,
    config     jsonb       NOT NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    module_id  integer     NOT NULL,
    CONSTRAINT pk_devices_id PRIMARY KEY (id),
    CONSTRAINT unq_module_logic_id UNIQUE (module_id, logic_id)
);
-- ddl-end --
ALTER TABLE public.devices OWNER TO smart_home_admin;
-- ddl-end --

-- object: public.logs | type: TABLE --
-- DROP TABLE IF EXISTS public.logs CASCADE;
CREATE TABLE public.logs
(
    id          integer     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    type        text        NOT NULL,
    content     text        NOT NULL,
    "timestamp" timestamptz NOT NULL DEFAULT NOW(),
    module_id   integer     NOT NULL,
    CONSTRAINT pk_logs_id PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.logs OWNER TO smart_home_admin;
-- ddl-end --

-- object: public.device_readings | type: TABLE --
-- DROP TABLE IF EXISTS public.device_readings CASCADE;
CREATE TABLE public.device_readings
(
    id            bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "timestamp"   timestamptz NOT NULL DEFAULT NOW(),
    value_text    text,
    value_numeric double precision,
    metadata      jsonb,
    device_id     integer     NOT NULL,
    CONSTRAINT pk_device_reading_id PRIMARY KEY (id, "timestamp"),
    CONSTRAINT chk_value CHECK ((value_numeric is not null and value_text is null) or
                                (value_numeric is null and value_text is not null))
) PARTITION BY RANGE ("timestamp");
-- ddl-end --
ALTER TABLE public.device_readings OWNER TO smart_home_admin;
-- ddl-end --

-- object: idx_devices_module_id | type: INDEX --
-- DROP INDEX IF EXISTS public.idx_devices_module_id CASCADE;
CREATE INDEX idx_devices_module_id ON public.devices
    USING btree
    (
    module_id
    );
-- ddl-end --

-- object: idx_device_readings_composite | type: INDEX --
-- DROP INDEX IF EXISTS public.idx_device_readings_composite CASCADE;
CREATE INDEX idx_device_readings_composite ON public.device_readings
    USING btree
    (
    device_id,
    "timestamp" DESC NULLS LAST
    )
    INCLUDE ("timestamp",value_text,value_numeric);
-- ddl-end --

-- object: idx_logs_module_id | type: INDEX --
-- DROP INDEX IF EXISTS public.idx_logs_module_id CASCADE;
CREATE INDEX idx_logs_module_id ON public.logs
    USING btree
    (
    module_id
    )
    INCLUDE (type,content,"timestamp");
-- ddl-end --

-- object: idx_logs_timestamp | type: INDEX --
-- DROP INDEX IF EXISTS public.idx_logs_timestamp CASCADE;
CREATE INDEX idx_logs_timestamp ON public.logs
    USING btree
    (
    "timestamp" DESC NULLS LAST
    )
    INCLUDE (type,content,module_id);
-- ddl-end --

-- object: public.notify_table_change | type: FUNCTION --
-- DROP FUNCTION IF EXISTS public.notify_table_change() CASCADE;
CREATE FUNCTION public.notify_table_change()
    RETURNS trigger
    LANGUAGE plpgsql
	VOLATILE
	CALLED ON NULL INPUT
	SECURITY INVOKER
	PARALLEL UNSAFE
	COST 1
	AS $$
BEGIN
    PERFORM
pg_notify(
        TG_TABLE_NAME || '_changed',
        json_build_object(
            'operation', TG_OP
        )::text
    );
RETURN NULL;
END;
$$;
-- ddl-end --
ALTER FUNCTION public.notify_table_change() OWNER TO smart_home_admin;
-- ddl-end --

-- object: modules_notify | type: TRIGGER --
-- DROP TRIGGER IF EXISTS modules_notify ON public.modules CASCADE;
CREATE TRIGGER modules_notify
    AFTER INSERT OR
DELETE
OR
UPDATE OF id,logic_address, name,config,created_at
ON public.modules
    FOR EACH STATEMENT
    EXECUTE PROCEDURE public.notify_table_change();
-- ddl-end --

-- object: devices_notify | type: TRIGGER --
-- DROP TRIGGER IF EXISTS devices_notify ON public.devices CASCADE;
CREATE TRIGGER devices_notify
    AFTER INSERT OR
DELETE
OR
UPDATE
    ON public.devices
    FOR EACH STATEMENT
    EXECUTE PROCEDURE public.notify_table_change();
-- ddl-end --

-- object: fk_modules_id_devices | type: CONSTRAINT --
-- ALTER TABLE public.devices DROP CONSTRAINT IF EXISTS fk_modules_id_devices CASCADE;
ALTER TABLE public.devices
    ADD CONSTRAINT fk_modules_id_devices FOREIGN KEY (module_id)
        REFERENCES public.modules (id) MATCH SIMPLE
        ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_modules_id_logs | type: CONSTRAINT --
-- ALTER TABLE public.logs DROP CONSTRAINT IF EXISTS fk_modules_id_logs CASCADE;
ALTER TABLE public.logs
    ADD CONSTRAINT fk_modules_id_logs FOREIGN KEY (module_id)
        REFERENCES public.modules (id) MATCH SIMPLE
        ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_devices_id_device_readings | type: CONSTRAINT --
-- ALTER TABLE public.device_readings DROP CONSTRAINT IF EXISTS fk_devices_id_device_readings CASCADE;
ALTER TABLE public.device_readings
    ADD CONSTRAINT fk_devices_id_device_readings FOREIGN KEY (device_id)
        REFERENCES public.devices (id) MATCH SIMPLE
        ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --


CREATE TABLE public.device_readings_default
    PARTITION OF public.device_readings DEFAULT;

ALTER TABLE public.device_readings_default OWNER TO smart_home_admin;
