-- Database generated with pgModeler (PostgreSQL Database Modeler).
-- pgModeler version: 1.0.0-beta1
-- PostgreSQL version: 15.0
-- Project Site: pgmodeler.io
-- Model Author: Paweł Dyczek
-- object: smart_home_admin | type: ROLE --
-- DROP ROLE IF EXISTS smart_home_admin;
CREATE ROLE smart_home_admin WITH LOGIN PASSWORD 'insert_password';
-- ddl-end --


-- Database creation must be performed outside a multi lined SQL file.
-- These commands were put in this file only as a convenience.
--
-- object: smart_home | type: DATABASE --
-- DROP DATABASE IF EXISTS smart_home;
-- CREATE DATABASE smart_home;
-- ddl-end --


-- object: public.modules | type: TABLE --
-- DROP TABLE IF EXISTS public.modules CASCADE;
CREATE TABLE public.modules
(
    id            integer     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    logic_address smallint    NOT NULL,
    name          varchar(64) NOT NULL,
    config        jsonb       NOT NULL,
    last_online   timestamptz,
    created_at    timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_modules_id PRIMARY KEY (id),
    CONSTRAINT unq_logic_address UNIQUE (logic_address)
);
-- ddl-end --
ALTER TABLE public.modules OWNER TO smart_home_admin;
-- ddl-end --

-- object: public.sensors | type: TABLE --
-- DROP TABLE IF EXISTS public.sensors CASCADE;
CREATE TABLE public.sensors
(
    id         integer     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    logic_id   smallint    NOT NULL,
    name       varchar(64) NOT NULL,
    type       varchar(64) NOT NULL,
    config     jsonb,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    module_id  integer     NOT NULL,
    CONSTRAINT pk_sensors_id PRIMARY KEY (id),
    CONSTRAINT unq_module_logic_id UNIQUE (module_id, logic_id)
);
-- ddl-end --
ALTER TABLE public.sensors OWNER TO smart_home_admin;
-- ddl-end --

-- object: public.logs | type: TABLE --
-- DROP TABLE IF EXISTS public.logs CASCADE;
CREATE TABLE public.logs
(
    id          integer     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    type        text        NOT NULL,
    content     text        NOT NULL,
    "timestamp" timestamptz NOT NULL DEFAULT NOW(),
    module_id   integer     NOT NULL,
    CONSTRAINT pk_logs_id PRIMARY KEY (id)
);
-- ddl-end --
ALTER TABLE public.logs OWNER TO smart_home_admin;
-- ddl-end --

-- object: public.sensor_readings | type: TABLE --
-- DROP TABLE IF EXISTS public.sensor_readings CASCADE;
CREATE TABLE public.sensor_readings
(
    id            bigint      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "timestamp"   timestamptz NOT NULL DEFAULT NOW(),
    value_text    text,
    value_numeric double precision,
    metadata      jsonb,
    sensor_id     integer     NOT NULL,
    CONSTRAINT pk_sensor_reading_id PRIMARY KEY (id, "timestamp"),
    CONSTRAINT chk_value CHECK ((value_numeric is not null and value_text is null) or
                                (value_numeric is null and value_text is not null))
) PARTITION BY RANGE ("timestamp");
-- ddl-end --
ALTER TABLE public.sensor_readings OWNER TO smart_home_admin;
-- ddl-end --

-- object: idx_sensors_module_id | type: INDEX --
-- DROP INDEX IF EXISTS public.idx_sensors_module_id CASCADE;
CREATE INDEX idx_sensors_module_id ON public.sensors
    USING btree
    (
    module_id
    );
-- ddl-end --

-- object: idx_sensor_readings_composite | type: INDEX --
-- DROP INDEX IF EXISTS public.idx_sensor_readings_composite CASCADE;
CREATE INDEX idx_sensor_readings_composite ON public.sensor_readings
    USING btree
    (
    sensor_id,
    "timestamp" DESC NULLS LAST
    )
    INCLUDE ("timestamp",value_text,value_numeric);
-- ddl-end --

-- object: idx_logs_module_id | type: INDEX --
-- DROP INDEX IF EXISTS public.idx_logs_module_id CASCADE;
CREATE INDEX idx_logs_module_id ON public.logs
    USING btree
    (
    module_id
    )
    INCLUDE (type,content,"timestamp");
-- ddl-end --

-- object: idx_logs_timestamp | type: INDEX --
-- DROP INDEX IF EXISTS public.idx_logs_timestamp CASCADE;
CREATE INDEX idx_logs_timestamp ON public.logs
    USING btree
    (
    "timestamp" DESC NULLS LAST
    )
    INCLUDE (type,content,module_id);
-- ddl-end --

-- object: fk_modules_id_sensors | type: CONSTRAINT --
-- ALTER TABLE public.sensors DROP CONSTRAINT IF EXISTS fk_modules_id_sensors CASCADE;
ALTER TABLE public.sensors
    ADD CONSTRAINT fk_modules_id_sensors FOREIGN KEY (module_id)
        REFERENCES public.modules (id) MATCH SIMPLE
        ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_modules_id_logs | type: CONSTRAINT --
-- ALTER TABLE public.logs DROP CONSTRAINT IF EXISTS fk_modules_id_logs CASCADE;
ALTER TABLE public.logs
    ADD CONSTRAINT fk_modules_id_logs FOREIGN KEY (module_id)
        REFERENCES public.modules (id) MATCH SIMPLE
        ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --

-- object: fk_sensors_id_sensor_readings | type: CONSTRAINT --
-- ALTER TABLE public.sensor_readings DROP CONSTRAINT IF EXISTS fk_sensors_id_sensor_readings CASCADE;
ALTER TABLE public.sensor_readings
    ADD CONSTRAINT fk_sensors_id_sensor_readings FOREIGN KEY (sensor_id)
        REFERENCES public.sensors (id) MATCH SIMPLE
        ON DELETE CASCADE ON UPDATE NO ACTION;
-- ddl-end --


CREATE TABLE public.sensor_readings_default
    PARTITION OF public.sensor_readings DEFAULT;

ALTER TABLE public.sensor_readings_default OWNER TO smart_home_admin;
